# @format

title: おちてはじまり、おちておわる。
description: 『おちてはじまり、おちておわる。』公式サイト
baseurl: ""
url: "http://127.0.0.1:4000"
include: [css, javascript, font, image]

# Jekyllのビルド対象から除外する設定
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .github
